os: windows

env:
    COMMIT_ID: 604051797b33ce9b5bf6350af0dada5482149e2c

install:
  
  # nanomsg
  - curl -L -o nanomsg.tar.gz https://github.com/nanomsg/nanomsg/archive/1.1.5.tar.gz
  - mkdir -p nanomsg
  - tar xf nanomsg.tar.gz --strip-components=1 -C nanomsg
  - cd nanomsg
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target install
  - cd ..
  - cd ..
  
  # protocol buffers
  - curl -L -o pb.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protobuf-cpp-3.11.4.tar.gz
  - mkdir -p pb
  - tar xf pb.tar.gz --strip-components=1 -C pb
  - cd pb
  - ./configure
  - make
  - sudo make install
  - cd ..
  
  # boost
  - curl -L -o boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
  - mkdir -p boost
  - tar xf boost.tar.bz2 --strip-components=1 -C boost
  - cd boost
  - ./bootstrap.sh --with-libraries=filesystem,system
  - sudo ./b2 -j4 threading=multi variant=release install
  - cd ..

script:
  - echo done
