
image: Visual Studio 2017

matrix:
  fast_finish: true

environment:
  COMMIT_ID: 604051797b33ce9b5bf6350af0dada5482149e2c
  CHERE_INVOKING: 'yes'  # Preserve the current working directory
  MSYSTEM: 'MINGW64'     # Start a 64 bit Mingw environment

install:

  # Update MSYS2
  - curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
  - curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
  - C:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig && pacman -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - C:\msys64\usr\bin\bash -lc "pacman -Syuu"  # Core update (in case any core packages are outdated)
  - C:\msys64\usr\bin\bash -lc "pacman -Syuu"  # Normal update
  
  # nanomsg
  - curl -L -o nanomsg.tar.gz https://github.com/nanomsg/nanomsg/archive/1.1.5.tar.gz
  - mkdir nanomsg
  - tar xf nanomsg.tar.gz --strip-components=1 -C nanomsg
  - cd nanomsg
  - mkdir build
  - cd build
  - cmake -A x64 ..
  - cmake --build . --target install --config Release
  - cd ..
  - cd ..
  
  # protocol buffers
  - curl -L -o pb.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protobuf-cpp-3.13.0.tar.gz
  - mkdir pb
  - tar xf pb.tar.gz --strip-components=1 -C pb
  - cd pb
  - C:\msys64\usr\bin\bash -lc "./configure"
#   - configure
#   - make
#   - sudo make install
#   - cd ..
  
  # boost
  - curl -L -o boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
  - mkdir boost
  - tar xf boost.tar.bz2 --strip-components=1 -C boost
  - cd boost
  - bootstrap.sh --with-libraries=filesystem,system
  - sudo ./b2 -j4 threading=multi variant=release install
  - cd ..

build_script:
  - echo done
